using CodeGenerator.Helper;
using CodeGenerator.Models;
using System.Security.Principal;

namespace CodeGenerator
{
    public class ControllerDataBaseGenerator
    {
        private readonly string _rootPath;
        private readonly List<string> _files;
        private readonly List<FileModel> _filesModel;
        private readonly string _destinyPath;

        public ControllerDataBaseGenerator(
            string rootPath,
            string destityPath)
        {
            _rootPath = rootPath;
            _destinyPath = destityPath;
            _files = [.. Directory.GetFiles(_rootPath)];
            _filesModel = Utilities.GetFilesModel(_files);
            Utilities.RegenerateDirectory(_destinyPath);
        }


        public List<string> GenerateForAllEntities()
        {
            List<string> responses = [];
            string response;

            List<FileModel> files = _filesModel.Where(x => x.Name.Substring(3, 1) == x.Name.Substring(3, 1).ToUpper()).ToList();

            foreach (FileModel file in files)
            {
                response = GenerateByEntity(file.Name);
                if (!string.IsNullOrEmpty(response))
                    responses.Add(response);
            }

            return responses;
        }

        public string GenerateByEntity(string entity)
        {
            string prefix;
            string entityUpper;
            string entityLower; 
            string init;

            try
            {
                prefix = entity[..3];
                init = entity.Substring(3, 1);
                entityUpper = string.Concat(init.ToUpper(), entity.AsSpan(4));
                entityLower = string.Concat(init.ToLower(), entity.AsSpan(4));

                GenerateController(prefix, entityUpper, entityLower);
                GenerateService(prefix, entityUpper, entityLower);

                return string.Empty;
            }
            catch (Exception ex)
            {
                return ex.Message + "|" + ex.StackTrace;
            }
        }

        public void GenerateController(string prefix, string entityUpper, string entityLower)
        {
            List<string> content;
            string controllerRoute;

            controllerRoute = "${BaseApi}/" + $"{entityLower}";

            content = [
                $"using Microsoft.AspNetCore.Authorization;",
                $"using Microsoft.AspNetCore.Mvc;",
                $"using SAMMAI.DataBase.Services.Implementations;",
                $"using SAMMAI.Transverse.Constants;",
                $"using SAMMAI.Transverse.Helpers;",
                $"using SAMMAI.Transverse.Models.Response.BaseApi;",
                $"using static SAMMAI.DataBase.Utility.Constants.ApiRoutesConstants;",
                $"",
                $"namespace SAMMAI.DataBase.Controllers",
                "{",
                $"    [Route(\"{controllerRoute}\")]",
                $"    [ApiController]",
                $"    public class {entityUpper}Controller : ControllerBase",
                "    {",
                $"        private readonly ILogger<{entityUpper}Controller> _logger;",
                $"        private readonly {entityUpper}Service _{entityLower}Service;",
                $"",
                $"        public {entityUpper}Controller(",
                $"            ILogger<{entityUpper}Controller> logger,",
                $"            {entityUpper}Service {entityLower}Service)",
                "        {",
                $"            _logger = logger ?? throw new ArgumentNullException(nameof(logger));",
                $"            _{entityLower}Service = {entityLower}Service ?? throw new ArgumentNullException(nameof({entityLower}Service));",
                "        }",
                $"",
                $"        #region Base Endpoints",
                $"        /// <summary>",
                $"        /// Gets a {entityUpper} by id",
                $"        /// </summary>",
                $"        /// <param name=\"id\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets a {entityUpper} by id",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns the {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"{{id}}\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetById(int id)",
                "        {",
                $"            {prefix}{entityUpper}Object? response = await _{entityUpper}Service.GetById(id);",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Gets a full {entityUpper} by id",
                $"        /// </summary>",
                $"        /// <param name=\"id\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets a full {entityUpper} by id",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns the full {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"{{id}}/full\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<View{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetFullById(int id)",
                "        {",
                $"            View{prefix}{entityUpper}Object? response = await _{entityUpper}Service.GetFullById (id);",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Gets a {entityUpper} by codigo",
                $"        /// </summary>",
                $"        /// <param name=\"codigo\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets a {entityUpper} by codigo",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns the {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"codigo/{{codigo}}\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetByCodigo(string codigo)",
                "        {",
                $"            {prefix}{entityUpper}Object? response = await _{entityUpper}Service.GetBycodigo(codigo);",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Gets a full {entityUpper} by codigo",
                $"        /// </summary>",
                $"        /// <param name=\"codigo\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets a full {entityUpper} by codigo",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns the full {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"codigo/{{codigo}}/full\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<View{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetFullByCodigo(string codigo)",
                "        {",
                $"            View{prefix}{entityUpper}Object? response = await _{entityUpper}Service.GetFullBycodigo(codigo);",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Gets all {entityUpper}",
                $"        /// </summary>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets all {entityUpper}",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns a list of {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"all\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetAll()",
                "        {",
                $"            List<{prefix}{entityUpper}Object>? response = await _{entityLower}Service.GetAll();",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Gets all full {entityUpper}",
                $"        /// </summary>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Gets all full {entityUpper}",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns a full list of {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpGet]",
                $"        [Route(\"all/full\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseSuccessApiResponseWithData<View{prefix}{entityUpper}Object>), (int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> GetAllFull()",
                "        {",
                $"            List<View{prefix}{entityUpper}Object>? response = await _{entityLower}Service.GetAllFull();",
                $"",
                $"            return Ok(ResponseHelper.SetSuccessResponseWithData(response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Insert a {entityUpper}",
                $"        /// </summary>",
                $"        /// <param name=\"{entityLower}></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Inserts a new {entityUpper}",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success: Returns the new {entityUpper} object</response>",
                $"        [AllowAnonymous]",
                $"        [HttpPost]",
                $"        [Route(\"insert\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType(typeof(BaseApiResponseWithData<{prefix}{entityUpper}Object>), (int)StatusCodeEnum.CREATED)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> Insert([FromBody] {prefix}{entityUpper}Object {entityLower})",
                "        {",
                $"            {prefix}{entityUpper}Object response = await _{entityLower}Service.Insert({entityLower});",
                $"",
                $"            return StatusCode((int)StatusCodeEnum.CREATED, ResponseHelper.SetResponseWithData(StatusCodeEnum.CREATED, response));",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Update a {entityUpper}",
                $"        /// </summary>",
                $"        /// <param name=\"{entityLower}\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Update a {entityUpper}",
                $"        /// </remarks>",
                $"        /// <response code=\"204\">No Content</response>",
                $"        [AllowAnonymous]",
                $"        [HttpPut]",
                $"        [Route(\"update\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType((int)StatusCodeEnum.NO_CONTENT)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> Update([FromBody] {prefix}{entityUpper}Object {entityLower})",
                "        {",
                $"            await _{entityLower}Service.Update({entityLower});",
                $"",
                $"            return NoContent();",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Activate or inactivate a {entityUpper} by id",
                $"        /// </summary>",
                $"        /// <param name=\"id\"></param>",
                $"        /// <param name=\"isActive\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Activate or inactivate a {entityUpper} by id",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success</response>",
                $"        [AllowAnonymous]",
                $"        [HttpPatch]",
                $"        [Route(\"{{id}}/active/{{isActive}}\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType((int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> SetActiveById(string id, bool active)",
                "        {",
                $"            await _{entityLower}Service.SetActiveById(id, isActive);",
                $"",
                $"            return Ok();",
                "        }",
                $"",
                $"        /// <summary>",
                $"        /// Activate or inactivate a {entityUpper} by codigo",
                $"        /// </summary>",
                $"        /// <param name=\"codigo\"></param>",
                $"        /// <param name=\"isActive\"></param>",
                $"        /// <returns></returns>",
                $"        /// <remarks>",
                $"        /// Activate or inactivate a {entityUpper} by codigo",
                $"        /// </remarks>",
                $"        /// <response code=\"200\">Success</response>",
                $"        [AllowAnonymous]",
                $"        [HttpPatch]",
                $"        [Route(\"codigo/{{codigo}}/active/{{isActive}}\")]",
                $"        [Produces(GeneralConstants.ContentType.Json)]",
                $"        [ProducesResponseType((int)StatusCodeEnum.OK)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.NOT_FOUND)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.BAD_REQUEST)]",
                $"        [ProducesResponseType(typeof(BaseBadRequestApiResponse), (int)StatusCodeEnum.INTERNAL_SERVER_ERROR)]",
                $"        public async Task<ActionResult<object>> SetActiveByCodigo(string codigo, bool active)",
                "        {",
                $"            await _{entityLower}Service.SetActiveByCodigo(codigo, isActive);",
                $"",
                $"            return Ok();",
                "        }",
                $"        #endregion",
                $"",
                $"        #region Custom Endpoints",
                $"",
                $"        #endregion",
                "    }",
                "}",
                $""
            ];

            GenerateFile("Controllers", $"{entityUpper}Controller.cs", content);
        }

        public void GenerateService(string prefix, string entityUpper, string entityLower)
        {
            List<string> content;

            content = [
                "using SAMMAI.DataBase.Repository.Context;",
                $"using SAMMAI.DataBase.Repository.Entities;",
                $"using SAMMAI.DataBase.Repository.Manager;",
                $"using SAMMAI.Transverse.Helpers;",
                $"",
                $"namespace SAMMAI.DataBase.Services.Implementations",
                "{",
                $"    public class {entityUpper}Service : BaseRepository<{prefix}{entityUpper}, View{prefix}{entityUpper}, SAMMAIContext>",
                "    {",
                $"        private readonly ILogger<{entityUpper}Service> _logger;",
                $"        private readonly SAMMAIContext _context;",
                $"        private readonly Global _global;",
                $"",
                $"        public {entityUpper}Service(",
                $"            ILogger<{entityUpper}Service> logger,",
                $"            SAMMAIContext context,",
                $"            Global global)",
                $"            : base(context)",
                "        {",
                $"            _logger = logger ?? throw new ArgumentNullException(nameof(logger));",
                $"            _context = context ?? throw new ArgumentNullException(nameof(context));",
                $"            _global = global ?? throw new ArgumentNullException(nameof(global));",
                "        }",
                $"",
                $"        #region Base Services",
                $"        public async Task<{prefix}{entityUpper}Object> GetById(int id)",
                "        {",
                $"            IEnumerable<{prefix}{entityUpper}> {entityLower}s = await GetFilteredAsync(x => x.Id == id && x.Eid == _global.Eid && x.Active);",
                $"",
                $"            if ({entityLower}s?.Any() == true)",
                $"                return {entityLower}s.ToList().FirstOrDefault();",
                $"",
                $"            throw new ApiException(StatusCodeEnum.NOT_FOUND);",
                "        }",
                $"",
                $"        public async Task<View{prefix}{entityUpper}Object> GetFullById(int id)",
                "        {",
                $"            IEnumerable<View{prefix}{entityUpper}> {entityLower}s = await GetViewFilteredAsync(x => x.Id == id && x.Eid == _global.Eid && x.Active);",
                $"",
                $"            if ({entityLower}s?.Any() == true)",
                $"                return {entityLower}s.ToList().FirstOrDefault();",
                $"",
                $"            throw new ApiException(StatusCodeEnum.NOT_FOUND);",
                "        }",
                $"",
                $"        public async Task<{prefix}{entityUpper}Object?> GetByCodigo(string codigo)",
                "        {",
                $"            IEnumerable<{prefix}{entityUpper}> {entityLower}s = await GetFilteredAsync(x => x.{entityUpper}Codigo == codigo && x.Eid == _global.Eid && x.Active);",
                $"",
                $"            if ({entityLower}s?.Any() == true)",
                $"                return {entityLower}s.ToList().FirstOrDefault();",
                $"",
                $"            throw new ApiException(StatusCodeEnum.NOT_FOUND);",
                "        }",
                $"",
                $"        public async Task<View{prefix}{entityUpper}Object?> GetFullByCodigo(string codigo)",
                "        {",
                $"            IEnumerable<View{prefix}{entityUpper}> {entityLower}s = await GetViewFilteredAsync(x => x.{entityUpper}Codigo == codigo && x.Eid == _global.Eid && x.Active);",
                $"",
                $"            if ({entityLower}s?.Any() == true)",
                $"                return {entityLower}s.ToList().FirstOrDefault();",
                $"",
                $"            throw new ApiException(StatusCodeEnum.NOT_FOUND);",
                "        }",
                $"",
                $"        public async Task<List<{prefix}{entityUpper}Object>?> GetAll()",
                "        {",
                $"            IEnumerable<{prefix}{entityUpper}> {entityLower}s = await GetFilteredAsync(x => x.Eid == _global.Eid && x.Active);",
                $"",
                $"            return {entityLower}s.ToList();",
                "        }",
                $"",
                $"        public async Task<List<View{prefix}{entityUpper}Object>?> GetAllFull()",
                "        {",
                $"            IEnumerable<View{prefix}{entityUpper}> {entityLower}s = await GetViewFilteredAsync(x => x.Eid == _global.Eid && x.Active);",
                $"",
                $"            return {entityLower}s.ToList();",
                "        }",
                $"",
                $"        public async Task<{prefix}{entityUpper}Object> Insert({prefix}{entityUpper}Object input)",
                "        {",
                $"            input.Eid = _global.Eid;",
                $"            input.Uid = _global.Uid;",
                $"            input.IdUsuarioCreo = _global.IdUsuario;",
                $"            input.IdUsuarioModifico = _global.IdUsuario;",
                $"            input.FechaCreacion = DateTime.Now;",
                $"            input.FechaModificacion = input.FechaCreacion;",
                $"            input.Active = true;",
                $"",
                $"            {prefix}{entityUpper}Object? {entityLower} = await AddAsync(input.ObjectToObject<{prefix}{entityUpper}>());",
                $"",
                $"            if ({entityLower} != null)",
                $"                return {entityLower};",
                $"",
                $"            throw new ApiException(StatusCodeEnum.BAD_REQUEST);",
                "        }",
                $"",
                $"        public async Task Update({prefix}{entityUpper}Object input)",
                "        {",
                $"            {prefix}{entityUpper}Object {entityLower}Object;",
                $"",
                $"            await GetById(input.Id);",
                $"",
                $"            input.Eid = _global.Eid;",
                $"            input.Uid = _global.Uid;",
                $"            input.IdUsuarioModifico = _global.IdUsuario;",
                $"            input.FechaModificacion = DateTime.Now;",
                $"            input.Active = true;",
                $"",
                $"            {entityLower}Object = await UpdateAsync(input.ObjectToObject<{prefix}{entityUpper}>());",
                $"",
                $"            if ({entityLower}Object is null)",
                $"                throw new ApiException(StatusCodeEnum.BAD_REQUEST);",
                "        }",
                $"",
                $"        public async Task SetActiveById(int id, bool active)",
                "        {",
                $"            {prefix}{entityUpper}Object {entityLower}Object;",
                $"",
                $"            {entityLower}Object = await GetById(id);",
                $"",
                $"            {entityLower}Object.Eid = _global.Eid;",
                $"            {entityLower}Object.Uid = _global.Uid;",
                $"            {entityLower}Object.IdUsuarioModifico = _global.IdUsuario;",
                $"            {entityLower}Object.FechaModificacion = DateTime.Now;",
                $"            {entityLower}Object.Active = active;",
                $"",
                $"            {entityLower}Object = await UpdateAsync({entityLower}Object.ObjectToObject<{prefix}{entityUpper}>());",
                $"",
                $"            if ({entityLower}Object is null)",
                $"                throw new ApiException(StatusCodeEnum.BAD_REQUEST);",
                "        }",
                $"",
                $"        public async Task SetActiveByCodigo(string codigo, bool active)",
                "        {",
                $"            {prefix}{entityUpper}Object {entityLower}Object;",
                $"",
                $"            {entityLower}Object = await GetByCodigo(codigo);",
                $"",
                $"            {entityLower}Object.Eid = _global.Eid;",
                $"            {entityLower}Object.Uid = _global.Uid;",
                $"            {entityLower}Object.IdUsuarioModifico = _global.IdUsuario;",
                $"            {entityLower}Object.FechaModificacion = DateTime.Now;",
                $"            {entityLower}Object.Active = active;",
                $"",
                $"            {entityLower}Object = await UpdateAsync({entityLower}Object.ObjectToObject<{prefix}{entityUpper}>());",
                $"",
                $"            if ({entityLower}Object is null)",
                $"                throw new ApiException(StatusCodeEnum.BAD_REQUEST);",
                "        }",
                $"        #endregion",
                $"",
                $"        #region Custom Services",
                $"",
                $"        #endregion",
                "    }",
                "}",
                $""
            ];

            GenerateFile("Services", $"{entityUpper}Service.cs", content);
        }

        #region Utilities
        private void GenerateFile(string directory, string file, List<string> content)
            => Utilities.GenerateFile(_destinyPath, directory, file, content);
        #endregion
    }
}
